# Configuración global del curso. Se carga antes de project() mediante
# CMakePresets.json o con -DCMAKE_TOOLCHAIN_FILE=config/course-toolchain.cmake.

set(COURSE_GCC_VERSION "15.3.0" CACHE STRING "Versión exacta esperada de GCC")
set(COURSE_C_STANDARD "17" CACHE STRING "Estándar C del curso")
set(COURSE_CXX_STANDARD "20" CACHE STRING "Estándar C++ del curso")
set(COURSE_OPENMP_VERSION "5.2" CACHE STRING "Versión normativa de OpenMP")
set(COURSE_MPI_IMPLEMENTATION "MPICH" CACHE STRING "Implementación MPI fijada")
set(COURSE_MPI_VERSION "5.0.1" CACHE STRING "Versión exacta de MPICH")
set(COURSE_MPI_STANDARD_VERSION "5" CACHE STRING "Versión mayor del estándar MPI")
set(COURSE_CUDA_VERSION "13.0" CACHE STRING "Versión de CUDA Toolkit")
set(COURSE_CUDA_ARCHITECTURES "75;80;86;89;90;100;120" CACHE STRING "Arquitecturas CUDA docentes")
set(COURSE_PYTHON_VERSION "3.14.6" CACHE STRING "Versión de Python para notebooks")

option(COURSE_STRICT_VERSIONS "Rechazar versiones distintas a las fijadas" ON)
option(COURSE_ENABLE_OPENMP "Configurar OpenMP" ON)
option(COURSE_ENABLE_MPI "Configurar MPICH/MPI" ON)
option(COURSE_ENABLE_CUDA "Configurar el módulo CUDA" OFF)
option(COURSE_ENABLE_NOTEBOOKS "Validar Python y librerías de notebooks" ON)

function(course_resolve_program output_variable environment_variable)
  set(names ${ARGN})
  if(DEFINED ENV{${environment_variable}} AND NOT "$ENV{${environment_variable}}" STREQUAL "")
    list(PREPEND names "$ENV{${environment_variable}}")
  endif()
  find_program(resolved_program NAMES ${names} NO_CACHE)
  if(NOT resolved_program)
    string(JOIN ", " expected_names ${names})
    message(FATAL_ERROR
      "No se encontró ${environment_variable}. Candidatos: ${expected_names}. "
      "Defina ${environment_variable} con una ruta absoluta.")
  endif()
  set(${output_variable} "${resolved_program}" PARENT_SCOPE)
endfunction()

course_resolve_program(course_c_compiler COURSE_CC gcc-15 gcc)
course_resolve_program(course_cxx_compiler COURSE_CXX g++-15 g++)
set(CMAKE_C_COMPILER "${course_c_compiler}" CACHE FILEPATH "Compilador C del curso" FORCE)
set(CMAKE_CXX_COMPILER "${course_cxx_compiler}" CACHE FILEPATH "Compilador C++ del curso" FORCE)

if(COURSE_ENABLE_MPI)
  set(course_mpi_hints)
  if(DEFINED ENV{COURSE_MPI_ROOT} AND NOT "$ENV{COURSE_MPI_ROOT}" STREQUAL "")
    list(APPEND course_mpi_hints "$ENV{COURSE_MPI_ROOT}/bin")
    set(MPI_HOME "$ENV{COURSE_MPI_ROOT}" CACHE PATH "Raíz de MPICH" FORCE)
  endif()
  find_program(course_mpicc NAMES mpicc HINTS ${course_mpi_hints} REQUIRED)
  find_program(course_mpicxx NAMES mpicxx mpic++ HINTS ${course_mpi_hints} REQUIRED)
  find_program(course_mpiexec NAMES mpiexec mpirun HINTS ${course_mpi_hints} REQUIRED)
  set(MPI_C_COMPILER "${course_mpicc}" CACHE FILEPATH "Wrapper MPI para C" FORCE)
  set(MPI_CXX_COMPILER "${course_mpicxx}" CACHE FILEPATH "Wrapper MPI para C++" FORCE)
  set(MPIEXEC_EXECUTABLE "${course_mpiexec}" CACHE FILEPATH "Lanzador MPICH" FORCE)
endif()

if(COURSE_ENABLE_CUDA)
  set(course_cuda_hints)
  if(DEFINED ENV{COURSE_CUDA_ROOT} AND NOT "$ENV{COURSE_CUDA_ROOT}" STREQUAL "")
    list(APPEND course_cuda_hints "$ENV{COURSE_CUDA_ROOT}/bin")
    set(CUDAToolkit_ROOT "$ENV{COURSE_CUDA_ROOT}" CACHE PATH "Raíz de CUDA Toolkit" FORCE)
  else()
    list(APPEND course_cuda_hints "/usr/local/cuda-${COURSE_CUDA_VERSION}/bin" "/usr/local/cuda/bin")
  endif()
  find_program(course_nvcc NAMES nvcc HINTS ${course_cuda_hints} REQUIRED)
  set(CMAKE_CUDA_COMPILER "${course_nvcc}" CACHE FILEPATH "Compilador CUDA" FORCE)
  set(CMAKE_CUDA_ARCHITECTURES "${COURSE_CUDA_ARCHITECTURES}" CACHE STRING "GPU targets" FORCE)
endif()
